# version: "3.8"

services:
  # PHP SERVICE
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    container_name: php
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis

  # Database Server
  database:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  # Redis Server
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6379:6379

volumes:
  db-data: ~
